server:
  port: 10000
  
zuul:
  routes:
    application:
      path: /application-service/**
      stripPrefix: false
      url: http://localhost:9090

logging:
  level:
    org.springframework.web: ERROR
    com.mkyong: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /Users/donnypissu/Documents/reframe/logs     